POST http://127.0.0.1:8000/api/users/signup
Content-Type: application/json

{ "username": "bob", "password": "Pass123!", "email": "bob@email.com" }

###

POST http://127.0.0.1:8000/api/users/login 
Content-Type: application/json
 
{ "username": "mike", "password": "Pass123!"}
 
###

GET http://127.0.0.1:8000/api/users/test_token 
Content-Type: application/json 
Authorization: Token 75bc2df4ba0f8a9125b216ed12373359cf8a3f4e

###

POST http://127.0.0.1:8000/api/users/logout
Content-Type: application/json 
Authorization: Token 75bc2df4ba0f8a9125b216ed12373359cf8a3f4e
